service: "amathon-hands-on-jinho1"

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ap-northeast-2

plugins:
    - serverless-offline


package:
  exclude:
    - dist/assets/**
    - public/**
    - tests/**
  include:
    - dist
    - src

functions:
  graphql:
    handler: handler.graphql
    memorySize: 512
    timeout: 5
    events:
      - http:
          path: /root
          method: ANY
          cors: true
      - http:
          path: /root/{proxy+}
          method: ANY
          cors: true
  testdic:
    handler: src/testdic/handler.graphql
    memorySize: 512
    timeout: 5
    events:
      - http:
          path: /testdic
          method: ANY
          cors: true
      - http:
          path: /testdic/{proxy+}
          method: ANY
          cors: true

custom:
  serverless-offline:
    port: 4000
