service: serverless-graphql-rest

frameworkVersion: ">=1.21.0 <2.0.0"

provider:
  name: jinho
  runtime: nodejs8.10
  stage: dev
  region: ap-northeast-2

plugins:
  - serverless-offline

custom:
  serverless-offline:
    port: 4000

functions:
  graphql:
    handler: handler.graphqlHandler
    events:
    - http:
        path: graphql
        method: post
        cors: true