service: "amathon-hands-on-jinho1"

provider:
  name: aws
  profile: jinho
  runtime: nodejs8.10
  stage: dev
  region: ap-northeast-2

plugins:
    - serverless-offline
    - serverless-webpack


package:
  exclude:
    - dist/assets/**
    - public/**
    - src/**
    - tests/**
  include:
    - dist

functions:
  renderer:
    handler: handler.render
    memorySize: 512
    timeout: 5
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true



custom:
  serverless-offline:
    port: 4000
  webpackIncludeModules: true