service: "amathon-hands-on"

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage}
  region: ap-northeast-2

functions:
  root:
    handler: rootHandler.graphql
    memorySize: 512
    timeout: 5
    events:
      - http:
          path: /root
          method: ANY
          cors: true
      - http:
          path: /root/{proxy+}
          method: ANY
          cors: true
  BookSchema:
    handler: bundle/BookSchema/handler.graphql
    memorySize: 512
    timeout: 5
    events:
      - http:
          path: /BookSchema
          method: ANY
          cors: true
      - http:
          path: /BookSchema/{proxy+}
          method: ANY
          cors: true
  DogSchema:
    handler: bundle/DogSchema/handler.graphql
    memorySize: 512
    timeout: 5
    events:
      - http:
          path: /DogSchema
          method: ANY
          cors: true
      - http:
          path: /DogSchema/{proxy+}
          method: ANY
          cors: true



package:
  exclude:
    - dist/assets/**
    - public/**
    - tests/**
  include:
    - dist
    - src

plugins:
  - serverless-offline

custom:
  serverless-offline:
    port: 4000
